version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/symfony/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 5
    - package-ecosystem: "docker"
      directory: "/.docker/php/"
      schedule:
          interval: daily
      open-pull-requests-limit: 5