server {
    listen  80 default;
    server_name  dev.mediApp.dev;
    root /www/symfony/public;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ ^/index\.php(/|$) {
        fastcgi_pass   php_devops:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/fpm_symfony_error.log;
    access_log /var/log/nginx/fpm_symfony_access.log;
}