name: pipeline CI

on:
    push:
        branches: ["dev", "addList"]
    pull_request:
        branches: ["dev"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: install checkout
              uses: actions/checkout@v5
              
            - name: check docker
              run: |
                  docker -v
                  docker compose version
                  
            - name: build docker
              run: docker compose -f docker-compose.yaml build
              
            - name: start all container
              run: docker compose up -d
              
            - name: wait only php devops container
              run: |
                  until docker compose exec -T php_devops php -v > /dev/null 2>&1; do
                  echo "wait again pls"
                  done
                  echo "ready for composer"
              
            - name: composer install
              run: |
                  docker compose exec -T php_devops composer install \
                  --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
             
            - name: run test
              run: docker compose exec -T php_devops php bin/phpunit --testdox
              
            - name: down container
              if: always()
              run: docker compose down