name: pipeline CI


on:
    push:
        branches: ["ci"]
    pull_request:
        branches: ["ci"]


jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        
        steps:
            - name: install checkout
              uses: actions/checkout@v5
              
            - name: check docker
              run: |
                  docker -v
                  docker compose version
                  
            - name: build docker
              run: docker compose -f docker-compose.yaml build